# Continuous integration test of any branch.

name: CI
on:
  push:
    branches-ignore:
    - main

jobs:
  # Run test suite
  test_suite:
    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v2'

    - name: Pytest
      run: |-
        python3 -mvenv venv
        . venv/bin/activate
        pip install --upgrade pip
        pip3 install -r test-requirements.txt
        pip3 install -r dev-requirements.txt
        pip install -e .
        pytest

  # Build Docker image
  build_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: 'actions/checkout@v2'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - name: Image
      run: |-
        TAG=$(git rev-parse --abbrev-ref HEAD)
        cd docker
        docker build --build-arg branch=$TAG -t us.gcr.io/broad-dsp-lrma/lr-longbow:$TAG .
        gcloud auth configure-docker -q
        docker push -q us.gcr.io/broad-dsp-lrma/lr-longbow:$TAG
