# Continuous integration test of any branch.

name: CI
on:
  push:
    branches-ignore:
    - main

jobs:
  # Build Docker image
  build_docker:
    runs-on: ubuntu-latest

    steps:
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
        project_id: broad-dsp-lrma
        export_default_credentials: true

    - name: Image
      run: |-
        cd docker && docker build -t us.gcr.io/broad-dsp-lrma/lr-longbow:kvgtest .

    - run: |
        gcloud auth configure-docker -q

    - name: Build
      run: |-
        docker push us.gcr.io/broad-dsp-lrma/lr-longbow:kvgtest
